// Initialize Icons
lucide.createIcons();

// State Management (Simulating Redux/Context)
const state = {
    user: null,
    currentSite: null,
    trialEndDate: null,
    isSubscribed: false,
    plans: {
        starter: { id: 'price_1', price: 19 },
        pro: { id: 'price_2', price: 49 },
        agency: { id: 'price_3', price: 149 }
    }
};

// 1. AI Generation Engine (Structured JSON Mock)
async function generateSite() {
    const prompt = document.getElementById('ai-prompt').value;
    if (!prompt) return alert("Please describe your business.");

    // Simulate API Call to Node.js/Prisma backend
    document.getElementById('view-container').innerHTML = `
        <div class="flex flex-col items-center justify-center h-96">
            <div class="generating text-blue-600 mb-4"><i data-lucide="loader" class="w-12 h-12 animate-spin"></i></div>
            <p class="text-xl font-medium">AI is designing your layout and writing copy...</p>
        </div>
    `;
    lucide.createIcons();

    setTimeout(() => {
        const mockAIResponse = {
            theme: { primary: "#2563eb", font: "Inter" },
            sections: [
                { type: 'nav', content: { logo: "AutoSite" } },
                { type: 'hero', content: { title: prompt.toUpperCase(), sub: "Generated by AutoSite AI for you." } },
                { type: 'features', items: ["Mobile Ready", "SEO Optimized", "AI Content"] }
            ]
        };
        renderEditor(mockAIResponse);
    }, 2000);
}

// 2. Dynamic Renderer (Next.js-like Component Architecture)
function renderEditor(data) {
    document.getElementById('hero-view').classList.add('hidden');
    const editor = document.getElementById('editor-view');
    editor.classList.remove('hidden');
    
    const preview = document.getElementById('site-preview');
    preview.innerHTML = data.sections.map(section => {
        if(section.type === 'hero') {
            return `
                <div class="py-20 px-10 text-center bg-white">
                    <h1 contenteditable="true" class="text-5xl font-bold mb-4">${section.content.title}</h1>
                    <p contenteditable="true" class="text-gray-600">${section.content.sub}</p>
                    <button class="mt-8 px-6 py-3 bg-blue-600 text-white rounded-lg">Get Started</button>
                </div>
            `;
        }
        return '';
    }).join('');
}

// 3. SaaS Subscription & Trial Logic
function handleSignup() {
    const now = new Date();
    state.user = { email: "user@example.com" };
    state.trialEndDate = new Date(now.setDate(now.getDate() + 30));
    
    document.getElementById('auth-modal').classList.add('hidden');
    document.getElementById('trial-badge').classList.remove('hidden');
    alert("30-Day Free Trial Started! Expiring on: " + state.trialEndDate.toLocaleDateString());
}

function openAuth() {
    document.getElementById('auth-modal').classList.remove('hidden');
}

// 4. Persistence Simulation (LocalStorage)
function publishSite() {
    // Check Trial Status
    const now = new Date();
    if (state.trialEndDate && now > state.trialEndDate && !state.isSubscribed) {
        return alert("Your trial has expired. Please upgrade to a Pro plan to publish.");
    }
    
    const siteId = Math.random().toString(36).substring(7);
    alert(`Site Published Live! \nURL: https://${siteId}.autosite.run`);
}
// --- Stripe Integration Logic ---
const STRIPE_PUBLISHABLE_KEY = 'pk_test_your_key_here'; // Replace with your real key

async function redirectToCheckout(planId) {
    console.log(`Initiating checkout for plan: ${planId}`);
    
    // In a real production environment, you would call your Node.js/Prisma backend:
    // const response = await fetch('/api/create-checkout-session', { method: 'POST', body: JSON.stringify({ planId }) });
    // const session = await response.json();
    
    alert(`Redirecting to Stripe for ${planId}...\nIn production, this opens the secure payment page.`);
    
    // Simulate successful payment callback
    setTimeout(() => {
        state.isSubscribed = true;
        document.getElementById('trial-badge').innerText = "PRO PLAN ACTIVE";
        document.getElementById('trial-badge').className = "px-3 py-1 bg-blue-100 text-blue-700 rounded-full text-xs font-bold";
        alert("Payment Successful! Your 30-day limit has been lifted.");
    }, 2000);
}

// --- Enhanced AI Component Library ---
function renderFeatureSection(items) {
    return `
        <div class="py-16 px-10 bg-slate-50 border-y">
            <div class="max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
                ${items.map(item => `
                    <div class="p-6 bg-white rounded-xl shadow-sm border border-slate-100">
                        <div class="w-10 h-10 bg-blue-100 text-blue-600 rounded-lg flex items-center justify-center mb-4">
                            <i data-lucide="check-circle" class="w-6 h-6"></i>
                        </div>
                        <h3 contenteditable="true" class="font-bold mb-2">${item}</h3>
                        <p contenteditable="true" class="text-sm text-slate-500 text-balance">High-quality description generated specifically for your niche.</p>
                    </div>
                `).join('')}
            </div>
        </div>
    `;
}

// Update the renderEditor function to include the features
function renderEditor(data) {
    document.getElementById('hero-view').classList.add('hidden');
    const editor = document.getElementById('editor-view');
    editor.classList.remove('hidden');
    
    const preview = document.getElementById('site-preview');
    let htmlContent = "";

    data.sections.forEach(section => {
        if(section.type === 'hero') {
            htmlContent += `
                <div class="py-20 px-10 text-center bg-white">
                    <h1 contenteditable="true" class="text-5xl font-extrabold mb-4 text-slate-900">${section.content.title}</h1>
                    <p contenteditable="true" class="text-xl text-slate-600 max-w-2xl mx-auto">${section.content.sub}</p>
                    <button class="mt-8 px-8 py-4 bg-blue-600 text-white rounded-full font-bold shadow-lg hover:scale-105 transition">Get Started Today</button>
                </div>`;
        }
        if(section.type === 'features') {
            htmlContent += renderFeatureSection(section.items);
        }
    });
    // Extend the global state
state.isVerified = false; 

// --- Verification Logic ---

function sendVerification() {
    const email = document.getElementById('reg-email').value;
    if (!email.includes('@')) return alert("Please enter a valid email.");
    
    state.user = { email: email };
    document.getElementById('display-email').innerText = email;
    
    // Switch UI steps
    document.getElementById('auth-step-1').classList.add('hidden');
    document.getElementById('auth-step-2').classList.remove('hidden');
}

function simulateEmailVerify() {
    // In production, this happens when the user clicks the link in their email
    // which hits an API endpoint like /api/auth/verify?token=...
    state.isVerified = true;
    state.trialEndDate = new Date(new Date().setDate(new Date().getDate() + 30));
    
    alert("Email verified successfully! You can now generate your site.");
    document.getElementById('auth-modal').classList.add('hidden');
    
    // Update UI
    document.getElementById('trial-badge').classList.remove('hidden');
    lucide.createIcons();
}

// --- The Guarded Generation Function ---

async function generateSite() {
    // SECURITY CHECK: Guard the AI Engine
    if (!state.user || !state.isVerified) {
        openAuth(); // Force the modal
        const statusMsg = !state.user ? "Please sign up first." : "Please verify your email to continue.";
        alert(statusMsg);
        return;
    }

    const prompt = document.getElementById('ai-prompt').value;
    if (!prompt) return alert("Please describe your business.");

    // Proceed with Generation...
    document.getElementById('view-container').innerHTML = `
        <div class="flex flex-col items-center justify-center h-96">
            <div class="generating text-blue-600 mb-4"><i data-lucide="loader" class="w-12 h-12 animate-spin"></i></div>
            <p class="text-xl font-medium">AI is designing your layout...</p>
        </div>
    `;
    
    // Simulating API call delay
    setTimeout(() => {
        const mockAIResponse = {
            theme: { primary: "#2563eb" },
            sections: [
                { type: 'hero', content: { title: prompt.toUpperCase(), sub: "Verified & AI-Generated Content" } },
                { type: 'features', items: ["Verified Analytics", "Secure Hosting", "Fast CDN"] }
            ]
        };
        renderEditor(mockAIResponse);
    }, 1500);
}

    preview.innerHTML = htmlContent;
    lucide.createIcons(); // Re-initialize icons for the new content
}
